import Link from "next/link";
import { notFound } from "next/navigation";
import { requireInternalSession } from "../../../../lib/blinko/internal-auth";
import { getCommercialOpportunity } from "../../../../lib/blinko/commercial-server";
import InternalTopbar from "../../InternalTopbar";
import styles from "../../interno.module.css";

const uuidPattern=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const STAGES:Record<string,string>={P00:"Identificado",P01:"Contato pendente",P02:"Contatado",P03:"Em qualificação",P04:"Oportunidade qualificada",P05:"Diagnóstico / triagem",P06:"Recomendação definida",P07:"Proposta em preparação",P08:"Proposta enviada",P09:"Negociação / ajustes",P10:"Aprovada comercialmente",P11:"Formalização pendente",P12:"Condição de início pendente",P13:"Onboarding",P14:"Pronto para operação"};
function text(v:unknown){return typeof v==="string"?v:v==null?"":String(v)}
function money(v:unknown){const n=Number(v);return Number.isFinite(n)?n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"}):"—"}
function localInput(v:unknown){const raw=text(v);if(!raw)return "";const d=new Date(raw);if(Number.isNaN(d.getTime()))return "";const parts=new Intl.DateTimeFormat("sv-SE",{timeZone:"America/Bahia",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(d);const get=(t:string)=>parts.find(p=>p.type===t)?.value??"";return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`}
const fieldStyle={width:"100%",border:"1px solid rgba(1,48,30,.16)",background:"rgba(255,255,255,.82)",color:"#08271b",borderRadius:12,padding:11,font:"inherit"};

type Props={params:Promise<{id:string}>;searchParams?:Promise<{status?:string}>};
function notice(status?:string){if(status==="stage_saved")return "Etapa e próxima ação atualizadas.";if(status==="interaction_saved")return "Interação registrada e próxima ação renovada.";if(status==="opportunity_closed")return "Oportunidade encerrada com histórico preservado.";if(status==="commercial_invalid")return "Revise os campos obrigatórios da oportunidade.";if(status==="commercial_blocked")return "A regra comercial bloqueou essa alteração. Oportunidades ativas exigem responsável, próxima ação e data; perdas exigem motivo.";if(status==="commercial_schema_pending")return "O módulo comercial oficial ainda não está disponível no banco conectado.";return null}

export default async function OpportunityPage({params,searchParams}:Props){
  const session=await requireInternalSession();const {id}=await params;const query=searchParams?await searchParams:{};if(!uuidPattern.test(id))notFound();
  const data=await getCommercialOpportunity(id);if(data.schemaReady&&!data.opportunity)notFound();
  const o=data.opportunity;const closed=Boolean(text(o?.outcome_status));const statusNotice=notice(query.status);
  return <main className={styles.page}><div className={styles.shell}><InternalTopbar user={session.user} active="commercial" />
    <div className={styles.hero} style={{paddingBottom:14}}><Link className={styles.back} href="/interno/comercial">← voltar ao Comercial</Link>{statusNotice?<div className={styles.notice} style={{marginTop:14}}>{statusNotice}</div>:null}</div>
    {!data.schemaReady?<div className={styles.notice}>Migração 021 ainda não disponível neste ambiente.</div>:o?<div className={styles.reviewShell}>
      <section className={styles.reviewCard} style={{borderColor:"rgba(239,59,127,.24)",background:"rgba(239,59,127,.025)"}}><span className={styles.eyebrow}>OPORTUNIDADE</span><h1 style={{fontFamily:"Georgia, 'Times New Roman', serif",fontSize:40,fontWeight:500}}>{text(o.company_name)||text(o.lead_company_name)||"Empresa"}</h1><p style={{opacity:.72}}>{text(o.stated_need)}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><span className={styles.badge}>{text(o.pipeline_stage)} · {STAGES[text(o.pipeline_stage)]}</span><span className={styles.badge}>Rota: {text(o.route)}</span><span className={styles.badge}>Fit: {text(o.fit)}</span><span className={styles.badge}>Saúde: {text(o.health)}</span>{closed?<span className={styles.badge}>Resultado: {text(o.outcome_status)}</span>:null}</div></section>
      <section className={styles.reviewCard}><span className={styles.eyebrow}>PRÓXIMA AÇÃO</span><h2>{text(o.next_action_title)||"Sem ação pendente"}</h2><p>Responsável: <strong>{text(o.owner_label)||"—"}</strong> · Canal: {text(o.next_action_channel)||"—"}</p><p>Valor estimado: <strong>{money(o.estimated_value)}</strong></p></section>
      {!closed?<>
      <section className={styles.reviewCard}><span className={styles.eyebrow}>ETAPA P00–P14</span><h2>Atualizar estágio e próxima ação</h2><form action={`/api/interno/comercial/${id}/stage`} method="post" className={styles.form}><label>Etapa<select name="stage" defaultValue={text(o.pipeline_stage)} style={fieldStyle}>{Object.entries(STAGES).map(([k,v])=><option key={k} value={k}>{k} — {v}</option>)}</select></label><label>Responsável<input name="owner_label" defaultValue={text(o.owner_label)||session.user} style={fieldStyle}/></label><label>Próxima ação<input name="next_action_title" defaultValue={text(o.next_action_title)} style={fieldStyle}/></label><label>Data da próxima ação<input name="next_action_at" type="datetime-local" defaultValue={localInput(o.next_action_at)} style={fieldStyle}/></label><label>Canal<input name="next_action_channel" defaultValue={text(o.next_action_channel)} style={fieldStyle}/></label><label>Nota da mudança<textarea name="notes" rows={3} style={fieldStyle}/></label><button className={styles.button} type="submit">Salvar etapa</button></form></section>
      <section className={styles.reviewCard}><span className={styles.eyebrow}>INTERAÇÃO</span><h2>Registrar contato e já definir o próximo passo</h2><form action={`/api/interno/comercial/${id}/interaction`} method="post" className={styles.form}><label>Canal<input name="channel" required style={fieldStyle} placeholder="WhatsApp, ligação, reunião, e-mail..."/></label><label>Resumo<textarea name="summary" rows={4} required style={fieldStyle}/></label><label>Próxima ação<input name="next_action_title" required style={fieldStyle}/></label><label>Data<input name="next_action_at" type="datetime-local" required style={fieldStyle}/></label><label>Canal da próxima ação<input name="next_action_channel" style={fieldStyle}/></label><button className={styles.button} type="submit">Registrar interação</button></form></section>
      <section className={styles.reviewCard} style={{borderColor:"rgba(120,50,50,.18)"}}><span className={styles.eyebrow}>SAÍDA DO PIPELINE</span><h2>Encerrar oportunidade</h2><form action={`/api/interno/comercial/${id}/close`} method="post" className={styles.form}><label>Resultado<select name="outcome" defaultValue="lost" style={fieldStyle}><option value="lost">Perdido</option><option value="nurture">Nutrição</option><option value="disqualified">Desqualificado</option><option value="paused">Pausado</option><option value="no_response">Sem resposta</option><option value="won">Ganho — somente em P14</option></select></label><label>Motivo de perda<select name="loss_reason" defaultValue="" style={fieldStyle}><option value="">Não se aplica / selecione se perdido</option><option value="price_investment">Preço / investimento</option><option value="priority_changed">Prioridade mudou</option><option value="no_budget">Sem orçamento</option><option value="no_response">Sem resposta</option><option value="competitor">Concorrente</option><option value="solution_mismatch">Solução não aderente</option><option value="deadline">Prazo</option><option value="postponed">Adiamento</option><option value="internal_decision">Decisão interna</option><option value="out_of_scope">Fora do escopo</option><option value="blinko_capacity">Capacidade da Blinko</option><option value="other">Outro</option></select></label><label>Observações<textarea name="loss_notes" rows={3} style={fieldStyle}/></label><button className={styles.button} type="submit">Encerrar oportunidade</button></form></section>
      </>:null}
      <section className={styles.reviewCard}><span className={styles.eyebrow}>HISTÓRICO</span><h2>Eventos da oportunidade</h2><div style={{display:"grid",gap:10,marginTop:12}}>{data.events.map(e=><article key={text(e.id)} style={{padding:14,border:"1px solid rgba(1,48,30,.1)",borderRadius:14}}><strong>{text(e.event_type)}</strong><small style={{display:"block",opacity:.65}}>{text(e.from_stage)}{text(e.to_stage)?` → ${text(e.to_stage)}`:""} · {text(e.actor_label)||"system"}</small>{text(e.summary)?<p style={{marginBottom:0}}>{text(e.summary)}</p>:null}</article>)}</div></section>
    </div>:null}
  </div></main>;
}
