-- Blinko OS — catálogo oficial do Diagnóstico Blinko v1.0
-- Fonte de autoridade: Documento 03 — BLINKO — DIAGNÓSTICO BLINKO, v1.0 · 09/09/2026.

insert into public.diagnostic_pillars_catalog(methodology_version,pillar_code,position,name,central_question,active) values
  ('blinko-diagnostic-v1','P01',1,'FUNDAMENTOS','A empresa sabe o que é, para quem existe, para onde vai e em quais bases está operando?',true),
  ('blinko-diagnostic-v1','P02',2,'MARCA','A empresa é reconhecível, coerente, diferenciada e protegida na medida necessária?',true),
  ('blinko-diagnostic-v1','P03',3,'OFERTA','Está claro o que a empresa vende, para quem, com que valor e em quais condições?',true),
  ('blinko-diagnostic-v1','P04',4,'COMERCIAL','A empresa possui um processo consistente para transformar oportunidades em vendas?',true),
  ('blinko-diagnostic-v1','P05',5,'MARKETING','A empresa está conseguindo ser encontrada, compreendida e lembrada pelas pessoas certas?',true),
  ('blinko-diagnostic-v1','P06',6,'CLIENTE','A experiência entregue sustenta a promessa feita pela empresa?',true),
  ('blinko-diagnostic-v1','P07',7,'OPERAÇÃO','A empresa consegue entregar o que vende com organização, padrão e responsabilidade clara?',true),
  ('blinko-diagnostic-v1','P08',8,'FINANCEIRO','A empresa conhece e controla a lógica econômica da própria operação?',true),
  ('blinko-diagnostic-v1','P09',9,'TECNOLOGIA','A tecnologia reduz trabalho, erro e dependência manual ou aumenta a desorganização?',true),
  ('blinko-diagnostic-v1','P10',10,'GESTÃO','A empresa consegue decidir, acompanhar pessoas e corrigir sua rota com base em informações reais?',true)
on conflict(methodology_version,pillar_code) do update set position=excluded.position,name=excluded.name,central_question=excluded.central_question,active=true;

insert into public.diagnostic_items_catalog(methodology_version,item_code,pillar_code,position,question,subtheme,active) values
  ('blinko-diagnostic-v1','F01','P01',1,'O modelo de negócio está claramente compreendido e pode ser explicado de forma objetiva?',null,true),
  ('blinko-diagnostic-v1','F02','P01',2,'A empresa possui propósito, missão, visão e valores coerentes com sua realidade atual?',null,true),
  ('blinko-diagnostic-v1','F03','P01',3,'Os responsáveis conseguem explicar quais objetivos a empresa pretende alcançar nos próximos 12 a 24 meses?',null,true),
  ('blinko-diagnostic-v1','F04','P01',4,'O público prioritário está definido com clareza suficiente para orientar decisões?',null,true),
  ('blinko-diagnostic-v1','F05','P01',5,'A empresa conhece o mercado em que compete, seus principais concorrentes e alternativas disponíveis ao cliente?',null,true),
  ('blinko-diagnostic-v1','F06','P01',6,'Os diferenciais declarados são reais, relevantes e percebidos pelo mercado?',null,true),
  ('blinko-diagnostic-v1','F07','P01',7,'Existe alguma análise estruturada de forças, fraquezas, oportunidades e ameaças ou equivalente?',null,true),
  ('blinko-diagnostic-v1','F08','P01',8,'As informações institucionais essenciais estão organizadas e atualizadas?',null,true),
  ('blinko-diagnostic-v1','F09','P01',9,'A estrutura societária, responsabilidades principais e forma básica de funcionamento estão claras internamente?',null,true),
  ('blinko-diagnostic-v1','F10','P01',10,'A empresa possui dependência excessiva de uma única pessoa para decisões ou conhecimento essencial?',null,true),
  ('blinko-diagnostic-v1','M01','P02',1,'O nome da empresa é adequado ao posicionamento e não apresenta conflito conhecido que exija investigação?',null,true),
  ('blinko-diagnostic-v1','M02','P02',2,'A situação de pesquisa, disponibilidade ou proteção do nome/marca está conhecida na medida necessária?',null,true),
  ('blinko-diagnostic-v1','M03','P02',3,'A identidade visual possui qualidade e consistência suficientes para representar a empresa?',null,true),
  ('blinko-diagnostic-v1','M04','P02',4,'Logo, cores, tipografia e elementos principais são utilizados de forma consistente?',null,true),
  ('blinko-diagnostic-v1','M05','P02',5,'O posicionamento da marca está claro e diferencia a empresa de alternativas relevantes?',null,true),
  ('blinko-diagnostic-v1','M06','P02',6,'A proposta de valor é compreensível para o público?',null,true),
  ('blinko-diagnostic-v1','M07','P02',7,'A identidade verbal, tom e forma de comunicação possuem coerência?',null,true),
  ('blinko-diagnostic-v1','M08','P02',8,'Os arquivos oficiais da marca estão organizados e acessíveis?',null,true),
  ('blinko-diagnostic-v1','M09','P02',9,'Os principais pontos de contato físicos e digitais apresentam a marca de forma consistente?',null,true),
  ('blinko-diagnostic-v1','M10','P02',10,'A reputação percebida sustenta a promessa da marca?',null,true),
  ('blinko-diagnostic-v1','O01','P03',1,'Produtos e serviços estão claramente definidos e organizados?',null,true),
  ('blinko-diagnostic-v1','O02','P03',2,'Cada oferta possui público, problema ou necessidade atendida bem compreendidos?',null,true),
  ('blinko-diagnostic-v1','O03','P03',3,'Benefícios e diferenciais são comunicados de forma objetiva?',null,true),
  ('blinko-diagnostic-v1','O04','P03',4,'Escopo, limites, entregáveis ou características da oferta estão claros?',null,true),
  ('blinko-diagnostic-v1','O05','P03',5,'Existe método minimamente confiável de precificação?',null,true),
  ('blinko-diagnostic-v1','O06','P03',6,'A empresa conhece custo e margem das principais ofertas na medida necessária?',null,true),
  ('blinko-diagnostic-v1','O07','P03',7,'O preço é coerente com posicionamento, mercado, capacidade de entrega e valor percebido?',null,true),
  ('blinko-diagnostic-v1','O08','P03',8,'O portfólio está simples o suficiente para ser vendido e operado sem confusão desnecessária?',null,true),
  ('blinko-diagnostic-v1','O09','P03',9,'A empresa conhece quais produtos ou serviços geram maior receita, margem ou recorrência?',null,true),
  ('blinko-diagnostic-v1','O10','P03',10,'Existem ofertas que consomem recursos sem retorno proporcional e precisam ser revistas?',null,true),
  ('blinko-diagnostic-v1','C01','P04',1,'As principais fontes de leads e oportunidades são conhecidas?',null,true),
  ('blinko-diagnostic-v1','C02','P04',2,'Existe padrão de resposta e tempo aceitável de primeiro atendimento comercial?',null,true),
  ('blinko-diagnostic-v1','C03','P04',3,'A empresa qualifica a oportunidade antes de preparar solução ou proposta?',null,true),
  ('blinko-diagnostic-v1','C04','P04',4,'Orçamentos e propostas seguem estrutura clara e consistente?',null,true),
  ('blinko-diagnostic-v1','C05','P04',5,'Regras de preço, desconto e negociação estão definidas na medida necessária?',null,true),
  ('blinko-diagnostic-v1','C06','P04',6,'Existe rotina de follow-up para propostas e oportunidades abertas?',null,true),
  ('blinko-diagnostic-v1','C07','P04',7,'Leads, propostas, negociações e clientes são registrados em CRM ou controle equivalente?',null,true),
  ('blinko-diagnostic-v1','C08','P04',8,'A empresa conhece sua taxa de conversão ou possui dados suficientes para estimá-la?',null,true),
  ('blinko-diagnostic-v1','C09','P04',9,'Os principais motivos de perda são registrados e analisados?',null,true),
  ('blinko-diagnostic-v1','C10','P04',10,'Existe visão de pipeline ou previsão comercial mínima?',null,true),
  ('blinko-diagnostic-v1','C11','P04',11,'A responsabilidade por cada oportunidade está clara?',null,true),
  ('blinko-diagnostic-v1','C12','P04',12,'Marketing e comercial compartilham informações suficientes para evitar perda de oportunidades?',null,true),
  ('blinko-diagnostic-v1','MK01','P05',1,'Os canais de marketing utilizados fazem sentido para o público e o modelo de negócio?',null,true),
  ('blinko-diagnostic-v1','MK02','P05',2,'A presença institucional no Google e mecanismos de descoberta está adequada quando aplicável?',null,true),
  ('blinko-diagnostic-v1','MK03','P05',3,'Perfis em redes sociais possuem informações corretas, apresentação coerente e caminhos claros de contato?',null,true),
  ('blinko-diagnostic-v1','MK04','P05',4,'Site, landing page ou presença web própria existe quando o negócio realmente necessita?',null,true),
  ('blinko-diagnostic-v1','MK05','P05',5,'Existe uma lógica de conteúdo ligada a marca, oferta, público e objetivo comercial?',null,true),
  ('blinko-diagnostic-v1','MK06','P05',6,'A comunicação evita depender exclusivamente de promoções ou publicações sem objetivo?',null,true),
  ('blinko-diagnostic-v1','MK07','P05',7,'Existe calendário ou planejamento mínimo de campanhas e sazonalidades relevantes?',null,true),
  ('blinko-diagnostic-v1','MK08','P05',8,'A empresa utiliza mídia paga apenas quando existe estrutura adequada para receber e acompanhar demanda?',null,true),
  ('blinko-diagnostic-v1','MK09','P05',9,'Há acompanhamento de métricas relevantes, sem confundir vaidade com resultado?',null,true),
  ('blinko-diagnostic-v1','MK10','P05',10,'É possível relacionar, ao menos parcialmente, esforços de marketing a geração de demanda, leads ou vendas?',null,true),
  ('blinko-diagnostic-v1','MK11','P05',11,'Materiais gráficos e promocionais possuem coerência visual e estratégica?',null,true),
  ('blinko-diagnostic-v1','MK12','P05',12,'Conteúdo, marca, oferta e processo comercial comunicam a mesma promessa?',null,true),
  ('blinko-diagnostic-v1','CL01','P06',1,'A jornada do cliente desde descoberta até pós-venda pode ser descrita claramente?',null,true),
  ('blinko-diagnostic-v1','CL02','P06',2,'O primeiro atendimento possui padrão mínimo de qualidade e clareza?',null,true),
  ('blinko-diagnostic-v1','CL03','P06',3,'WhatsApp, telefone, e-mail e outros canais estão organizados e adequados à demanda?',null,true),
  ('blinko-diagnostic-v1','CL04','P06',4,'O cliente recebe orientações claras depois da compra ou contratação?',null,true),
  ('blinko-diagnostic-v1','CL05','P06',5,'Durante a entrega, existe comunicação suficiente sobre status, prazo e próximos passos?',null,true),
  ('blinko-diagnostic-v1','CL06','P06',6,'Reclamações, falhas e imprevistos possuem processo de resolução definido?',null,true),
  ('blinko-diagnostic-v1','CL07','P06',7,'A empresa realiza algum tipo de pós-venda?',null,true),
  ('blinko-diagnostic-v1','CL08','P06',8,'Satisfação, avaliações, depoimentos ou reclamações são coletados e analisados?',null,true),
  ('blinko-diagnostic-v1','CL09','P06',9,'Existe estratégia ou processo para estimular recompra, renovação, indicação ou fidelização quando aplicável?',null,true),
  ('blinko-diagnostic-v1','CL10','P06',10,'Informações importantes sobre cada cliente ficam registradas e acessíveis à equipe autorizada?',null,true),
  ('blinko-diagnostic-v1','CL11','P06',11,'A experiência real é coerente com a promessa feita no marketing e na venda?',null,true),
  ('blinko-diagnostic-v1','CL12','P06',12,'Existem pontos da jornada em que clientes frequentemente desistem, reclamam ou ficam sem resposta?',null,true),
  ('blinko-diagnostic-v1','OP01','P07',1,'Os processos principais de entrega podem ser descritos de início a fim?',null,true),
  ('blinko-diagnostic-v1','OP02','P07',2,'Papéis e responsabilidades estão claros?',null,true),
  ('blinko-diagnostic-v1','OP03','P07',3,'Rotinas críticas possuem procedimentos, checklists ou padrões na medida necessária?',null,true),
  ('blinko-diagnostic-v1','OP04','P07',4,'Tarefas e projetos possuem algum controle de status, prazo e responsável?',null,true),
  ('blinko-diagnostic-v1','OP05','P07',5,'A empresa conhece sua capacidade aproximada de atendimento ou produção?',null,true),
  ('blinko-diagnostic-v1','OP06','P07',6,'Prazos prometidos são compatíveis com a capacidade real?',null,true),
  ('blinko-diagnostic-v1','OP07','P07',7,'Existe controle de qualidade antes da entrega ao cliente?',null,true),
  ('blinko-diagnostic-v1','OP08','P07',8,'Arquivos, documentos e informações operacionais estão organizados de forma recuperável?',null,true),
  ('blinko-diagnostic-v1','OP09','P07',9,'A operação depende excessivamente da memória ou presença de pessoas específicas?',null,true),
  ('blinko-diagnostic-v1','OP10','P07',10,'Fornecedores e parceiros críticos possuem escopo e responsabilidade minimamente claros?',null,true),
  ('blinko-diagnostic-v1','OP11','P07',11,'Retrabalhos, erros recorrentes e gargalos operacionais são registrados ou conhecidos?',null,true),
  ('blinko-diagnostic-v1','OP12','P07',12,'Estrutura física, equipamentos e ambiente de trabalho são adequados à operação quando aplicável?',null,true),
  ('blinko-diagnostic-v1','FI01','P08',1,'Finanças da empresa e finanças pessoais estão separadas na medida necessária?',null,true),
  ('blinko-diagnostic-v1','FI02','P08',2,'Entradas e saídas são registradas de forma consistente?',null,true),
  ('blinko-diagnostic-v1','FI03','P08',3,'Existe controle de contas a pagar e a receber?',null,true),
  ('blinko-diagnostic-v1','FI04','P08',4,'O fluxo de caixa atual e futuro é acompanhado?',null,true),
  ('blinko-diagnostic-v1','FI05','P08',5,'Os principais custos fixos e variáveis são conhecidos?',null,true),
  ('blinko-diagnostic-v1','FI06','P08',6,'A precificação utiliza custos, margem e outros critérios relevantes?',null,true),
  ('blinko-diagnostic-v1','FI07','P08',7,'A margem das principais ofertas é conhecida ou pode ser calculada?',null,true),
  ('blinko-diagnostic-v1','FI08','P08',8,'Existe acompanhamento de resultado, lucro ou demonstrativo equivalente adequado ao porte?',null,true),
  ('blinko-diagnostic-v1','FI09','P08',9,'A empresa conhece sua necessidade de capital de giro e compromissos próximos?',null,true),
  ('blinko-diagnostic-v1','FI10','P08',10,'Inadimplência e cobrança são controladas quando aplicável?',null,true),
  ('blinko-diagnostic-v1','FI11','P08',11,'É possível identificar quais produtos, serviços, projetos ou unidades são mais rentáveis?',null,true),
  ('blinko-diagnostic-v1','FI12','P08',12,'Existe rotina minimamente organizada de interface com contador ou responsável financeiro?',null,true),
  ('blinko-diagnostic-v1','T01','P09',1,'A empresa conhece quais sistemas e ferramentas utiliza e para qual finalidade?',null,true),
  ('blinko-diagnostic-v1','T02','P09',2,'Dados essenciais estão centralizados ou distribuídos de forma controlada?',null,true),
  ('blinko-diagnostic-v1','T03','P09',3,'Existe CRM ou solução equivalente quando o volume comercial justifica?',null,true),
  ('blinko-diagnostic-v1','T04','P09',4,'Tarefas repetitivas relevantes já foram identificadas como candidatas à automação?',null,true),
  ('blinko-diagnostic-v1','T05','P09',5,'Sistemas importantes trocam informações adequadamente ou exigem retrabalho de digitação?',null,true),
  ('blinko-diagnostic-v1','T06','P09',6,'Acessos, senhas e permissões são administrados de forma minimamente segura?',null,true),
  ('blinko-diagnostic-v1','T07','P09',7,'Arquivos e dados essenciais possuem backup ou forma confiável de recuperação?',null,true),
  ('blinko-diagnostic-v1','T08','P09',8,'Existem controles básicos de segurança compatíveis com o risco da empresa?',null,true),
  ('blinko-diagnostic-v1','T09','P09',9,'A equipe utiliza efetivamente as ferramentas contratadas?',null,true),
  ('blinko-diagnostic-v1','T10','P09',10,'Existem planilhas, mensagens ou controles paralelos que geram duplicidade e inconsistência?',null,true),
  ('blinko-diagnostic-v1','T11','P09',11,'A tecnologia atual é proporcional ao porte e à complexidade da operação?',null,true),
  ('blinko-diagnostic-v1','T12','P09',12,'Existe oportunidade clara de digitalização sem automatizar um processo ainda desorganizado?',null,true),
  ('blinko-diagnostic-v1','G01','P10',1,'Existe planejamento de curto e médio prazo com prioridades claras?',null,true),
  ('blinko-diagnostic-v1','G02','P10',2,'Metas relevantes estão definidas e possuem responsável?',null,true),
  ('blinko-diagnostic-v1','G03','P10',3,'Indicadores essenciais são acompanhados com frequência adequada?',null,true),
  ('blinko-diagnostic-v1','G04','P10',4,'Há rotina de reunião ou revisão de desempenho quando o porte exige?',null,true),
  ('blinko-diagnostic-v1','G05','P10',5,'Decisões importantes são registradas de forma recuperável?',null,true),
  ('blinko-diagnostic-v1','G06','P10',6,'Planos de ação possuem responsáveis, prazos e acompanhamento?',null,true),
  ('blinko-diagnostic-v1','G07','P10',7,'Sócios e líderes conseguem distinguir urgência diária de prioridade estratégica?',null,true),
  ('blinko-diagnostic-v1','G08','P10',8,'Existe clareza de papéis de liderança e tomada de decisão?',null,true),
  ('blinko-diagnostic-v1','G09','P10',9,'A equipe recebe orientação, treinamento ou onboarding adequados às funções críticas?',null,true),
  ('blinko-diagnostic-v1','G10','P10',10,'Existe alguma rotina de feedback e acompanhamento de desempenho de pessoas quando aplicável?',null,true),
  ('blinko-diagnostic-v1','G11','P10',11,'A empresa utiliza dados suficientes para decidir sobre investimento, expansão ou corte?',null,true),
  ('blinko-diagnostic-v1','G12','P10',12,'A gestão revisa processos e prioridades quando o contexto muda?',null,true)
on conflict(methodology_version,item_code) do update set pillar_code=excluded.pillar_code,position=excluded.position,question=excluded.question,subtheme=excluded.subtheme,active=true;
